In [2]:
import numpy as np

In [7]:
myarr = np.array([[3,6,99999,7]], np.float64)

In [8]:
myarr[0,1]

6.0

In [9]:
myarr.dtype

dtype('float64')

In [10]:
myarr.shape

(1, 4)

In [11]:
myarr[0,1] = 45

In [12]:
myarr

array([[3.0000e+00, 4.5000e+01, 9.9999e+04, 7.0000e+00]])

# Array creation: Conversion from other Python structures

In [13]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [14]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [15]:
listarray.dtype

dtype('int32')

In [16]:
listarray.shape

(3, 3)

In [17]:
listarray.size

9

In [18]:
np.array({34,23,23}) #creates objects, which are not very efficient

array({34, 23}, dtype=object)

In [19]:
zeros = np.zeros((2,5))

In [20]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
rng = np.arange(15)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace = np.linspace(1,5,12)

In [24]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
lspace = np.linspace(1,50,10) # 10 elements from 1 to 50

In [26]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [27]:
emp =np.empty((4,6)) #makes an empty array of 4,6 
                     #and fills with random numbers

In [28]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.06811354e-306, 1.15710971e-306, 1.69118787e-306],
       [1.78021527e-306, 1.42413555e-306, 1.78019082e-306,
        1.37959740e-306, 6.23057349e-307, 1.02360935e-306],
       [1.69120416e-306, 1.78022342e-306, 6.23058028e-307,
        1.06811422e-306, 9.45699680e-308, 1.11258854e-306],
       [1.11261502e-306, 1.42410839e-306, 7.56597770e-307,
        6.23059726e-307, 1.42419530e-306, 7.56599128e-307]])

In [30]:
emp_like = np.empty_like(lspace) #takes shape from lspace, 
                    #creates empty array and fills with random numbers

In [31]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [32]:
ide = np.identity(45) #45X45 identity mtrix is printed

In [33]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [34]:
ide.shape

(45, 45)

In [35]:
arr = np.arange(99)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr = arr.reshape(3,33) #needs to be factor of number of elements 
                    #in array to be reshaped

In [41]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [42]:
arr = arr.ravel() #makes arr a 1d array

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
arr.shape

(99,)

In [45]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [46]:
ar  = np.array(x)

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
ar.sum(axis=0)

array([12,  8,  9])

In [49]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [50]:
ar.T #transposes array ar

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [51]:
ar.flat #gives an iterator

In [53]:
for item in ar.flat: #applies the iterator to ar
    print(item)

1
2
3
4
5
6
7
1
0


In [54]:
ar.ndim

2

In [56]:
ar.size

9

In [57]:
ar.nbytes

36

In [64]:
one =np.array([1,3,4,634,2]) #maximum element at 3 index, min at 0 index

In [65]:
one.argmax() #bracket gives a method, w/o brakcet is an attribute

3

In [66]:
one.argmin()

0

In [67]:
one.argsort() #sorts indices by value of elements in increasing order

array([0, 4, 1, 2, 3], dtype=int64)

In [68]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [71]:
ar.argmin() #flattens array and tells value of minimum element

8

In [72]:
ar.argmax() #flattens array and tells value of maximum element

6

In [73]:
ar.argmax(axis=0) #goes axiswise

array([2, 1, 1], dtype=int64)

In [74]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [75]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [76]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [77]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [80]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [82]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [83]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [84]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [85]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [86]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [87]:
ar.sum()

29

In [88]:
ar.max()

7

In [89]:
ar.min()

0

In [90]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [93]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [94]:
type(np.where(ar>5))

tuple

In [95]:
np.count_nonzero(ar) #tells count of non zero elements

8

In [97]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [98]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [99]:
ar [1,2] = 0

In [100]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [101]:
ar

array([[1, 2, 3],
       [4, 5, 0],
       [7, 1, 0]])

In [102]:
import sys

In [104]:
py_ar =[0,4,55,2] 

In [105]:
np_ar = np.array(py_ar)

In [108]:
sys.getsizeof(1) * len(py_ar) #getsizeof(n) size of n element

112

In [109]:
len(py_ar)

4

In [110]:
np_ar.itemsize * np_ar.size #ar.itemsize represents size of an item in array 'ar'
#ar.size represents size of array 'ar'

16

In [111]:
np_ar.tolist() #converts numpy array to list

[0, 4, 55, 2]